name: swing_tiger
description: "SwingTiger Admin Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  firebase_core: ^3.15.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.1
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.0.1

  excel: ^4.0.6
  file_picker: ^8.1.2 
  
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  url_launcher: ^6.3.0

  geolocator: ^13.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/swingtiger_logo_02.png" # 사용할 로고 파일명 확인하세요
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/swingtiger_logo_02.png"
  min_pad_ratio: 0.5

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
    - family: DoHyeon
      fonts:
        - asset: assets/fonts/DoHyeon-Regular.ttf